Handle title text on images
gitterHQ/gitter-markdown-processor pull request #9
Opened 2017-04-10 13:08 UTC by keawade

Resolves #8.

2017-04-10 18:09 UTC, MadLittleMods commented
How does this handle image syntax without the title? It looks like it might `undefined` or empty string in the attributes which is undesired.

```
![This is alt text](https://www.gitter.im/)
```

2017-04-10 18:21 UTC, keawade commented
I'm not certain, but I suspect you are correct. I'll check that this evening and correct it as needed.

2017-04-11 00:22 UTC, keawade commented
@MadLittleMods Okay, I've resolved the `null` title issue and added a test for that case.

2017-04-11 01:17 UTC, MadLittleMods requested changes

2017-04-11 01:17 UTC, MadLittleMods commented on lib/process-chat.js
> +      return util.format('<img src="%s" alt="%s" rel="nofollow">', href, text)
Missing semicolon

2017-04-11 01:18 UTC, MadLittleMods commented
@keawade Looks fine. Just a small nit 😀

2017-04-11 01:21 UTC, keawade commented
Whoops, my bad. Fixed.

2017-04-11 01:22 UTC, merged

2017-04-11 01:24 UTC, MadLittleMods commented
Thanks for the contribution @keawade 🎉